load("@crates//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "camos_bootinfo",
    aliases = aliases(),
    deps = all_crate_deps(
        normal = True,
    ),
    proc_macro_deps = all_crate_deps(
        proc_macro = True,
    ),
    srcs = glob(["src/**/*.rs"]),
    # rustc_flags = ["-Cpanic=abort"],
    visibility = ["//visibility:public"],
)